https://docs.pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html

In [2]:
pip install torch torchvision

Note: you may need to restart the kernel to use updated packages.


# Tensors
Tensors are a specialized data structure that are very **similar to arrays and matrices**. In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model’s parameters.

Tensors are similar to `NumPy’s ndarrays`, except that tensors **can run on GPUs or other hardware accelerators.** In fact, tensors and NumPy arrays can often `share the same underlying memory`, eliminating the need to copy data (see Bridge with NumPy). 

In [3]:
import torch
import numpy as np

## Initializing Tensors
1. Directly from Data
2. From Numpy array
3. From another Tensor
4. With random Constant Values

In [4]:
# Direcly from Data
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print("Tensor from data:", x_data)

Tensor from data: tensor([[1, 2],
        [3, 4]])


In [5]:
# From NumPy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print("Tensor from NumPy array:", x_np)

Tensor from NumPy array: tensor([[1, 2],
        [3, 4]])


In [6]:
# From another tensor
# (shape, datatype)
x_ones = torch.ones_like(x_data)  # retains the properties of x_data  
# ones_like : new tensor with same shape as x_data but filled with ones  
print("Tensor of ones like x_data:", x_ones)

x_rand = torch.rand_like(x_data, dtype=torch.float) 
# rand_like : new tensor with same shape as x_data but with random values
print("Tensor of ones like x_data with float dtype:", x_rand)

x_zeros = torch.zeros_like(x_data)
# zeros_like : new tensor with same shape as x_data but filled with zeros
print("Tensor of zeros like x_data:", x_zeros)

Tensor of ones like x_data: tensor([[1, 1],
        [1, 1]])
Tensor of ones like x_data with float dtype: tensor([[0.7438, 0.6427],
        [0.0863, 0.9148]])
Tensor of zeros like x_data: tensor([[0, 0],
        [0, 0]])


In [7]:
# With random or constant values
# shape is a tuple of tensor dimensions. 
# In the functions below, it determines the dimensionality of the output tensor.
shape = (2, 3,)  # tuple of tensor dimensions

rand_tensor = torch.rand(shape) # random values
ones_tensor = torch.ones(shape) # ones
zeros_tensor = torch.zeros(shape) # zeros

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.9172, 0.4717, 0.9464],
        [0.9432, 0.4495, 0.2796]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## Attributes of a Tensor

Tensor attributes describe their shape, datatype, and the device on which they are stored.

In [8]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Operations on Tensors
https://docs.pytorch.org/docs/stable/torch.html : over 1200 operation documentations
These operations can be run outside our CPU. Refer to [this page](./0_Background.ipynb).
By default, we use CPU but we can move it to GPU or other accelerators using `to()`

In [9]:
# We move our tensor to the current accelerator if available
if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())

AttributeError: module 'torch' has no attribute 'accelerator'

아놔 참고로 위는 구석기 시대 문서이기 때문에 나오는 에러입니다.
```python
torch.cuda
torch.backends.mps
````
이제는 직접 체크해야함.

In [10]:
print(torch.backends.mps.is_available())

True


### 탬플릿

# 

In [11]:
import torch

if torch.cuda.is_available():
    device = torch.device("cuda")
elif torch.backends.mps.is_available():
    device = torch.device("mps")
else:
    device = torch.device("cpu")

print("Using device:", device)

tensor = tensor.to(device)

Using device: mps


### Try some operations
1. Standard numpy-like indexing and slicing

In [12]:
# 1. Standard numpy-like indexing and slicing
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


2. Joining Tensors with `torch.cat`

In [13]:
t1 = torch.cat([tensor, tensor, tensor], dim=1) # concatenate tensors along columns
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


3. Arithmetic operations

In [14]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
# ``tensor.T`` returns the transpose of a tensor
y1 = tensor @ tensor.T          # @ : matrix multiplication operator
y2 = tensor.matmul(tensor.T)    # matmul : matrix multiplication function

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)


# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor                # * : element-wise product operator
z2 = tensor.mul(tensor)             # mul : element-wise product function

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

4. Single-element tensors
If you have a `one-element tensor`, for example by aggregating all values of a tensor into one value, you can **convert it to a Python numerical value** using `item()`:

In [16]:
agg = tensor.sum()       # sum of all elements
print(agg)
print("---")

agg_item = agg.item()   # get the Python number from a tensor containing a single value
print(agg_item, type(agg_item))

tensor(12.)
---
12.0 <class 'float'>


5. In-place operations 
> **in-place 연산 = 새 텐서를 만들지 않고, 원래 텐서 자체를 바로 바꾸는 연산**

Operations that **store the result into the operand** are called `in-place`. They are denoted by a _ suffix. For example: x.copy_(y), x.t_(), will change x.

in-place 이해 못 하면 나중에 autograd / backprop에서 지옥을 맛본다고..
> **In-place operations save some memory, but can be problematic when computing derivatives because of an immediate loss of history. Hence, their use is discouraged.**

In [18]:
# Out of Place Operations
x = torch.tensor([1., 2., 3.])
y = x + 1 # out of place addition

print(x)  # tensor([1., 2., 3.])
print(y)  # tensor([2., 3., 4.])

tensor([1., 2., 3.])
tensor([2., 3., 4.])


In [19]:
# In-place operations
# Operations that have a trailing underscore ``_`` change the tensor in-place. For example:
x = torch.tensor([1., 2., 3.])
x.add_(1) # in-place addition using add_

print(x)  # tensor([2., 3., 4.])

tensor([2., 3., 4.])


## Bridge with NumPy

Tensors on the CPU and NumPy arrays **can share their underlying memory locations**, and changing one will change the other.

-> Tensor to NumPy array <-> Numpy array to Tensor 가 가능함
* `.numpy()` : converts tensor->Numpy
* `from_numpy()`: converts Numpy -> tensor

In [20]:
# Tensor to NumPy array
t = torch.ones(5)
n = t.numpy()        #.numpy() converts a tensor to a NumPy array
print("Tensor:", t)

Tensor: tensor([1., 1., 1., 1., 1.])


In [21]:
# NumPy array to Tensor
n = np.ones(5)
t = torch.from_numpy(n) # .from_numpy() converts a NumPy array to a tensor
print("NumPy array:", n)

NumPy array: [1. 1. 1. 1. 1.]
