# NumPy ufuncs
## What are ufuncs?
ufuncs stands for "Universal Functions" and they are NumPy functions that operate on the ndarray object.

## Why use ufuncs?
ufuncs are used to `implement vectorization in NumPy` which is way **faster than iterating over elements.**
> * NOTE : NumPy에서 브로드캐스팅(broadcasting) 이란, **형태(shape)가 다른 배열끼리도 자동으로 크기를 맞춰 연산할 수 있게 해주는 규칙**
They also provide **broadcasting** and additional methods like reduce, accumulate etc. that are very helpful for computation.

ufuncs also take additional arguments, like:

* `where` boolean array or condition defining where the operations should take place.

* `dtype` defining the return type of elements.

* `out` output array where the return value should be copied.

## What is Vectorization?
Converting iterative statements into a vector based operation is called vectorization.

It is faster as modern CPUs are optimized for such operations.

Add the Elements of Two Lists
```python
list 1: [1, 2, 3, 4]

list 2: [4, 5, 6, 7]
````

One way of doing it is to iterate over both of the lists and then sum each elements.

ExampleGet your own Python Server
Without ufunc, we can use Python's built-in zip() method:
```python
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = []

for i, j in zip(x, y):
  z.append(i + j)
print(z)
```
NumPy has a ufunc for this, called add(x, y) that will produce the same result.

Example
With ufunc, we can use the add() function:

import numpy as np
```python
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = np.add(x, y)

print(z)
```

----

# How To Create Your Own ufunc 
## `frompyfunc(fcn, ip,op)`

You can do this!

To create your own ufunc, you have to define a function, like you do with normal functions in Python, then you add it to your NumPy ufunc library with the frompyfunc() method.

The frompyfunc() method takes the following arguments:

* function - the name of the function.
* inputs - the number of input arguments (arrays).
* outputs - the number of output arrays.


In [1]:
import numpy as np

def myadd(x, y):
  return x+y

myadd = np.frompyfunc(myadd, 2, 1)

print(myadd([1, 2, 3, 4], [5, 6, 7, 8]))

[6 8 10 12]


## Check if a Function is a ufunc `(type())``

ufunc should return `<class 'numpy.ufunc'>`

In [4]:
# import numpy as np
print(type(np.add))
print(type(np.concatenate))
print(type(np.blahblah))

<class 'numpy.ufunc'>
<class 'numpy._ArrayFunctionDispatcher'>


AttributeError: module 'numpy' has no attribute 'blahblah'

To test if the function is a `ufunc in an if statement`, use the `numpy.ufunc value` (or np.ufunc if you use np as an alias for numpy):

In [5]:
if type(np.add) == np.ufunc:
  print('add is ufunc')
else:
  print('add is not ufunc')

add is ufunc


---
# Simple Arithmetic

## Simple Arithmetic
You could **use arithmetic operators `+ - * /` directly between NumPy arrays**, but this section discusses an extension of the same where we have functions that can **take any array-like objects** e.g. lists, tuples etc. and perform arithmetic conditionally.

> Arithmetic Conditionally: means that we can define conditions where the arithmetic operation should happen.

All of the discussed arithmetic functions take a where parameter in which we can specify that condition.

## Addition
The` add()` function sums the content of two arrays, and return the results in a new array.

### Example
Add the values in arr1 to the values in arr2:

```python
import numpy as np

arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.add(arr1, arr2)

print(newarr)

```

The example above will return [30 32 34 36 38 40] which is the sums of 10+20, 11+21, 12+22 etc.

## Subtraction
The `subtract()` function subtracts the values from one array with the values from another array, and return the results in a new array.

### Example
Subtract the values in arr2 from the values in arr1:

```python
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.subtract(arr1, arr2)
print(newarr)
```

The example above will return [-10 -1 8 17 26 35] which is the result of 10-20, 20-21, 30-22 etc.


## Multiplication
> ** Element-wise Multiplication (원소별 곱)임.. dot product 아님**
The `multiply()` function multiplies the values from one array with the values from another array, and return the results in a new array.

### Example
Multiply the values in arr1 with the values in arr2:

```py
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.multiply(arr1, arr2)

print(newarr)
```
The example above will return [200 420 660 920 1200 1500] which is the result of 10*20, 20*21, 30*22 etc.

## Division
The divide() function divides the values from one array with the values from another array, and return the results in a new array.

### Example
Divide the values in arr1 with the values in arr2:
```py
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])

newarr = np.divide(arr1, arr2)

print(newarr)
```

The example above will return [3.33333333 4. 3. 5. 25. 1.81818182] which is the result of 10/3, 20/5, 30/10 etc.

## Power
The power() function rises the values from the first array to the power of the values of the second array, and return the results in a new array.

### Example
Raise the valules in arr1 to the power of values in arr2:
```py
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 33])

newarr = np.power(arr1, arr2)

print(newarr)
```
The example above will return [1000 3200000 729000000 6553600000000 2500 0] which is the result of 10*10*10, 20*20*20*20*20, 30*30*30*30*30*30 etc.

## Remainder
Both the mod() and the remainder() functions return the remainder of the values in the first array corresponding to the values in the second array, and return the results in a new array.

### Example
Return the remainders:

```py
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.mod(arr1, arr2)

print(newarr)
```
The example above will return [1 6 3 0 0 27] which is the remainders when you divide 10 with 3 (10%3), 20 with 7 (20%7) 30 with 9 (30%9) etc.

You get the same result when using the remainder() function:

Example
Return the remainders:

```py
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.remainder(arr1, arr2)

print(newarr)
```

## Quotient and Mod
The `divmod() function` return both the `quotient and the mod`. The return value is two arrays, the first array contains the quotient and second array contains the mod.

## Example
Return the quotient and mod:
```py
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.divmod(arr1, arr2)

print(newarr)
```
The example above will return:
(array([3, 2, 3, 5, 25, 1]), array([1, 6, 3, 0, 0, 27]))
The first array represents the quotients, (the integer value when you divide 10 with 3, 20 with 7, 30 with 9 etc.
The second array represents the remainders of the same divisions.

## Absolute Values
Both the **absolute() and the abs() functions do the same** absolute operation element-wise but we should `use absolute() to avoid confusion with python's inbuilt math.abs()`

### Example
Return the absolute values of the array:
```python
import numpy as np

arr = np.array([-1, -2, 1, 2, 3, -4])

newarr = np.absolute(arr)

print(newarr)
```
The example above will return [1 2 1 2 3 4].

---

# Rounding Decimals

## Rounding Decimals
There are primarily five ways of rounding off decimals in NumPy:

* truncation
* fix
* rounding
* floor `.floor()`
* ceil `.ceil()`


## Truncation `.trunc()`, `.fix()`

Remove the decimals, and return the float number closest to zero. Use the trunc() and fix() functions.

In [8]:
arr = np.trunc([-3.1666, 3.6667])
print(arr)

[-3.  3.]


In [7]:
arr = np.fix([-3.1666, 3.6667])
print(arr)

[-3.  3.]


# Rounding `.around(num, decimal)`
> round 가 아니라 around라니..
The around() function increments preceding digit or decimal by 1 if >=5 else do nothing.

E.g. round off to 1 decimal point, 3.16666 is 3.2

In [12]:
arr = np.around(3.1666, 2) # 2 decimal places
print(arr)
# 오... 벡터도 가능함
arr = np.around([2.2432, 324.34223], 2) # -2 means round to hundreds place
print(arr)

3.17
[  2.24 324.34]


---

# NumPy Logs
## Logs
NumPy provides functions to perform log at the `base 2`, `e` and `10`

We will also explore how we can take log for any base by creating a custom ufunc.

All of the log functions will place `-inf` or `inf` in the elements **if the log can not be computed**

# Log at Base 2 `.log2()`
Use the log2() function to perform log at the base 2.

In [14]:
arr = np.arange(1, 10) # 1 to 9
print(np.log2(arr)) # log base 2

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


> Note: The arange(1, 10) function returns an array with integers starting from 1 (included) to 10 (not included).

## Log at Base 10 `log10()`
Use the `log10()` function to perform log at the base 10.

## Example
Find log at base 10 of all elements of following array:

In [15]:
arr = np.arange(1, 10) # 1 to 9
print(np.log10(arr)) # log base 10

[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


## Natural Log, or Log at Base e `log()`
Use the log() function to perform log at the base e.

### Example
Find log at base e of all elements of following array:

In [17]:
arr = np.arange(1, 10)
print(np.log(arr)) # natural log

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


## Log at Any Base
**NumPy does not provide any function to take log at any base**, so we can** use the `frompyfunc()` function along with inbuilt function `math.log()` **with two input parameters and one output parameter:

In [19]:
from math import log
import numpy as np

nplog = np.frompyfunc(log, 2, 1) # 2 inputs, 1 output
print(nplog(100, 15))            # log base 15 of 100

1.7005483074552052


---
# NumPy Summations
## Summations
What is the difference between `summation` and `addition`?

Addition is done **between two arguments** whereas summation happens **over n elements**

In [20]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.add(arr1, arr2)
print(newarr)
newarr2 = np.sum([arr1, arr2])
print(newarr2)

[2 4 6]
12


## Summation Over an Axis
If you specify `axis=1`, NumPy will sum the numbers in each array.

In [22]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

newarr = np.sum([arr1, arr2], axis=1)

print(newarr)

[ 6 15]


## Cummulative Sum `cumsum()`
Cummulative sum means **partially adding the elements in array**

E.g. The partial sum of [1, 2, 3, 4] would be [1, 1+2, 1+2+3, 1+2+3+4] = [1, 3, 6, 10].

Perfom partial sum with the cumsum() function

In [24]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = np.cumsum(arr, axis=1) # cumulative sum along rows
print(newarr)

[[ 1  3  6]
 [ 4  9 15]]


---

# NumPy Products
## Products prod()`
To find the product of the elements in an array, use the prod() function.

In [26]:
arr = np.array([1, 2, 3, 4])
x = np.prod(arr) # 1*2*3*4 = 24
print(x)

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

y = np.prod([arr1, arr2]) # 1*2*3*4*5*6*7*8

print(y)

24
40320


## Product Over an Axis
If you specify axis=1, NumPy will return the product of each array.

In [27]:
newarr = np.prod([arr1, arr2], axis=1) # product along each array
print(newarr)

[  24 1680]


## Cummulative Product `cumprod()`
Cummulative product means taking the product partially.

E.g. The partial product of [1, 2, 3, 4] is [1, 1*2, 1*2*3, 1*2*3*4] = [1, 2, 6, 24]

Perfom partial sum with the cumprod() function.

In [28]:

arr = np.array([5, 6, 7, 8])
newarr = np.cumprod(arr)
print(newarr)

[   5   30  210 1680]


---
# NumPy Differences

## Differences `diff()`

> **arr에서 연속한 원소의 차이를 계산**

A discrete difference means subtracting two successive elements.

E.g. for [1, 2, 3, 4], the discrete difference would be [2-1, 3-2, 4-3] = [1, 1, 1]

To find the discrete difference, use the diff() function.

In [29]:
arr = np.array([10, 15, 25, 5])
newarr = np.diff(arr)
print(newarr)

[  5  10 -20]


We can perform this operation repeatedly by giving `parameter n`

E.g. for [1, 2, 3, 4], the discrete difference with n = 2 would be [2-1, 3-2, 4-3] = [1, 1, 1] , then, since n=2, we will do it once more, with the new result: [1-1, 1-1] = [0, 0]

### Difference?
* 1차 차분 → 바로 옆 원소끼리 뺌
* 2차 차분 → 1차 차분 결과에서 연속된 값끼리 또 뺌
* 3차 차분 → 2차 차분에서 연속 값끼리 뺌

### why ?
* 데이터 변화량 확인 → 예: 주가, 센서값, 신호 분석
* 추세 제거 → 시계열 분석에서 주로 사용
* 수치 미분 근사 → 수치해석에서 derivative 대신

Compute discrete difference of the following array twice:

In [32]:
arr = np.array([10, 15, 25, 5])
newarr = np.diff(arr, n=2) # 2nd order difference 길이 = len(arr) - 2
print(newarr)

newwarr2 =np.diff(arr, n=3) # 3rd order difference 길이 = len(arr) - 3
print(newwarr2)

[  5 -30]
[-35]


> **[5 -30] because: 15-10=5, 25-15=10, and 5-25=-20 AND 10-5=5 and -20-10=-30**

---

# NumPy LCM Lowest Common Multiple

## Finding LCM (Lowest Common Multiple) `.lcm()`
The Lowest Common Multiple is the smallest number that is a common multiple of two numbers.

In [37]:
num1 = 4
num2 = 6
x = np.lcm(num1, num2)
print(x)

arr = np.array([3, 6, 9])
y = np.lcm.reduce(arr) # 3*6=18, 6*3=18 and 9*2=18
print(y)

# .reduce() : applies the function cumulatively to the items of an array, 
# from left to right, so as to reduce the array to a single value.
arr = np.arange(1, 11)
z = np.lcm.reduce(arr)

print(z)

12
18
2520


---
# NumPy GCD Greatest Common Divisor 
## Finding GCD (Greatest Common Divisor) `.gcd()`
The GCD (Greatest Common Divisor), also known as HCF (Highest Common Factor) is the biggest number that is a common factor of both of the numbers.


In [38]:
num1 = 6
num2 = 9

x = np.gcd(num1, num2)

print(x)

# .reduce() : To find the Highest Common Factor of all values in an array
rr = np.array([20, 8, 32, 36, 16])
x = np.gcd.reduce(arr)
print(x)

3
1


# NumPy Trigonometric Functions

## Trigonometric Functions
NumPy provides the ufuncs `sin(), cos() and tan()` that take values in radians and produce the corresponding sin, cos and tan values.

In [40]:
x = np.sin(np.pi/2)
print(x)

arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
x = np.sin(arr)
print(x)

1.0
[1.         0.8660254  0.70710678 0.58778525]


## Convert Degrees Into Radians `.deg2rad()`
By default all of the trigonometric functions take radians as parameters but we can convert radians to degrees and vice versa as well in NumPy.

>**Note: radians values are pi/180 * degree_values.**

In [41]:
arr = np.array([90, 180, 270, 360])
x = np.deg2rad(arr)
print(x)

[1.57079633 3.14159265 4.71238898 6.28318531]


## Radians to Degree

In [42]:
arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
x = np.rad2deg(arr)
print(x)

[90. 60. 45. 36.]


## Finding Angles
Finding angles from values of sine, cos, tan. E.g. sin, cos and tan inverse (arcsin, arccos, arctan).

NumPy provides ufuncs `arcsin(), arccos() and arctan()` that **produce radian values for corresponding sin, cos and tan values given.**

In [44]:
# Find the angle of 1.0:

x = np.arcsin(1.0)
print(x)

arr = np.array([1, -1, 0.1])
x = np.arcsin(arr)
print(x)

1.5707963267948966
[ 1.57079633 -1.57079633  0.10016742]


## Hypotenues `hotpot()`

Finding hypotenues using **pythagoras theorem in NumPy**

NumPy provides the hypot() function that takes the base and perpendicular values and produces hypotenues based on pythagoras theorem.


In [47]:
base = 3
perp = 4
x = np.hypot(base, perp)

print(x)

x = np.hypot(base, 30) # 30 instead of perp
print(x)

5.0
30.14962686336267



---

# NumPy Hyperbolic Functions



## Hyperbolic Functions
NumPy provides the ufuncs `sinh(), cosh() and tanh()` that take values in radians and produce the corresponding sinh, cosh and tanh values..
### Example
Find sinh value of PI/2:

In [49]:
x = np.sinh(np.pi/2)
print(x)

arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
x = np.cosh(arr)
print(x)

2.3012989023072947
[2.50917848 1.60028686 1.32460909 1.20397209]


## Finding Angles

Finding angles from values of hyperbolic sine, cos, tan. E.g. sinh, cosh and tanh inverse (arcsinh, arccosh, arctanh).

Numpy provides ufuncs `arcsinh(), arccosh() and arctanh()` that produce radian values for corresponding sinh, cosh and tanh values given.

In [50]:
x = np.arcsinh(1.0)
print(x)

arr = np.array([0.1, 0.2, 0.5])
x = np.arctanh(arr)
print(x)

0.881373587019543


# NumPy Set Operations

## What is a Set
A set in mathematics is a `collection` of unique elements.

Sets are used for operations involving `frequent intersection, union and difference operations`.

## Create Sets in NumPy `.unique()`
We can use NumPy's `unique()` method to **find unique elements from any array**. E.g. create a set array, but remember that the **set arrays should only be 1-D arrays**

In [51]:
arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])
x = np.unique(arr)
print(x)

[1 2 3 4 5 6 7]


## Finding Union `union1d()`
To find the unique values of two arrays, use the union1d() method.

In [52]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])
newarr = np.union1d(arr1, arr2)
print(newarr)

[1 2 3 4 5 6]


## Finding Intersection `intersect1d()` 
To find only the values that are present in both arrays, use the `intersect1d()` method.

In [53]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])
newarr = np.intersect1d(arr1, arr2, assume_unique=True)

print(newarr)

[3 4]


> Note: the intersect1d() method takes an optional argument assume_unique, which if set to True can speed up computation. It should always be set to True when dealing with sets.

## Finding Difference `setdiff1d()`
To find only the values in the **first set** that **is NOT present in the seconds** set, use the setdiff1d() method.

In [54]:
set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setdiff1d(set1, set2, assume_unique=True) # this returns elements in set1 not in set2

print(newarr)

[1 2]


> Note: the setdiff1d() method takes an optional argument assume_unique, which if set to True can speed up computation. It should always be set to True when dealing with sets.

##  Finding Symmetric Difference `setxor1d()`
To find only the values that are **NOT present in BOTH sets**, use the setxor1d() method.
공통인자 뺴고 전부 프린트

In [55]:
set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])
newarr = np.setxor1d(set1, set2, assume_unique=True)

print(newarr)

[1 2 5 6]


> Note: the setxor1d() method takes an optional argument assume_unique, which if set to True can speed up computation. It should always be set to True when dealing with sets.