# NumPy에서 행렬 계산 정리
multiply / dot / matmul / @ / einsum

## 1 Element-wise Multiplication (원소별 곱)
함수: `np.multiply(a, b)` 또는 `a * b`
* 각 인덱스끼리 그냥 곱함

In [1]:
import numpy as np
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[10, 20],
              [30, 40]])

A * B

array([[ 10,  40],
       [ 90, 160]])

## 2. Dot Product (Inner Product)

함수: `np.dot(a, b)`
* 1차원 배열(벡터)에서: 내적 (스칼라 나옴)
* 2차원 이상에서는: 행렬 곱과 비슷하게 동작

In [2]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.dot(a, b)

32

## 3. Matrix Multiplication (행렬 곱)
함수: `np.matmul(a, b)` 또는 연산자: `a @ b` (가장 많이 쓰임)
* 2차원: 우리가 아는 행렬 곱
* 1차원: 특별 규칙이 있음

In [3]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[10, 20],
              [30, 40]])

A @ B

array([[ 70, 100],
       [150, 220]])

## 4. einsum (Einstein Summation Notation)
einsum은 텐서 연산을 수식처럼 제어하는 강력한 도구.

Vector inner Product

In [4]:
np.einsum('i,i->', a, b)

32

행렬 곱

In [5]:
np.einsum('ik,kj->ij', A, B)

array([[ 70, 100],
       [150, 220]])

행렬 대각선만 추출

In [6]:
np.einsum('ii->i', A)

array([1, 4])